########### IMPORTS #####################
# NOTE: run this script from the root directory of the project to avoid path issues 

import argparse
import os
import json
import re
from util.preprocessing import parse_iob2_file
from eval import evaluate_predictions

import time
from datetime import timedelta

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from openai import OpenAI

#################### ---------HELPER FUNCTIONS--------- ################################
# TODO: fix annotate_chunk into smaller pieces:
# generate_raw_output()
# parse_output()
# validate_output()

# different model configurations
def load_model(model_name, quantized=False):

    if model_name == "gpt": #configuration is slightly different for API based models
        client = OpenAI()
        return {
            "backend": "openai",
            "client": client,
            "model_name": "gpt-5.4"
        }

    # if not gpt, continue loading a local model using Hugging Face Transformers
    elif model_name == "mistral":
        hf_name = "mistralai/Mistral-7B-Instruct-v0.3"

    elif model_name == "llama":
        hf_name = "meta-llama/Meta-Llama-3-8B-Instruct"

    else:
        raise ValueError(f"Unsupported model name: {model_name}")


    tokenizer = AutoTokenizer.from_pretrained(hf_name, trust_remote_code=True)

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    tokenizer.padding_side = "left"

    model_kwargs = {
    "device_map": "auto",
    "trust_remote_code": True,
    "use_safetensors": True
}

    if quantized:
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4"
        )

        print("Loading model in 4-bit quantized mode...\n")

        model_kwargs["quantization_config"] = bnb_config

    else:
        print("Loading model in full precision mode...\n")
        model_kwargs["torch_dtype"] = torch.float16

    model = AutoModelForCausalLM.from_pretrained(hf_name, **model_kwargs)
    model.eval()

    return {
        "backend": "hf",
        "model_name": hf_name,
        "model": model,
        "tokenizer": tokenizer
    }


# create flattened lists of sentences of max length to parse in one iteration through the model,
# and keep a track of the original sentence boundaries to be able to reconstruct the output into sentences after annotation
def build_chunks(sentences, labels=None, max_chunk_size=250): #usable both in validation or annotation mode according to labels
    chunks = []
    current_chunk = {
        "size": 0,
        "tokens": [], 
        "sent_lengths": [], 
        "sent_indices": [], 
        "gold_labels": [] if labels else None}

    for i, sent in enumerate(sentences): # remember sent is a list of tokens
        sent_len = len(sent) # how are we gonna handle extremely long sentences? for now they are treated separately as their own chunk

        # if adding the next sentence would exceed the max chunk size, finalize the current chunk and start a new one
        if current_chunk["size"] + sent_len > max_chunk_size:
            chunks.append(current_chunk)

            current_chunk = {
                "size": 0,
                "tokens": [], 
                "sent_lengths": [], 
                "sent_indices": [], 
                "gold_labels": [] if labels else None}

        # add sentence metadata to  current chunk
        current_chunk["tokens"].extend(sent)
        current_chunk["size"] += sent_len
        current_chunk["sent_lengths"].append(sent_len)
        current_chunk["sent_indices"].append(i)

        if labels:
            current_chunk["gold_labels"].append(labels[i])

    # add any remaining sentences as the last chunk
    if current_chunk["tokens"]:
        chunks.append(current_chunk)

    return chunks


# style prompt, ready to inject specific input text
def format_prompt(template_path, example_path):
    with open(template_path, "r", encoding="utf-8") as f:
        template = f.read()

    with open(example_path, "r", encoding="utf-8") as f:
        example_input = []
        example_output = []

        for line in f:
            line = line.strip()

            if not line or line.startswith("#"):
                continue

            _, token, label = line.split('\t')
            example_input.append(token)
            example_output.append([token, label])

    prompt_template = template.format(
    example_input=json.dumps(example_input),
    example_output=json.dumps(example_output)
)

    return prompt_template


# helper function to extract the JSON from the text generated by the LLM
def extract_json(text):
    match = re.search(r'\[.*\]', text, re.DOTALL)
    if not match:
        raise ValueError("No JSON found")
    return match.group(0)
    

# strict validation of model response format and content 
def validate_response(pred_labels, chunk):

    allowed_labels = {
        "B-PER", "I-PER",
        "B-ORG", "I-ORG",
        "B-LOC", "I-LOC",
        "O"
    }

    # check that the predicted labels list has the same length as the input tokens
    if len(pred_labels) != len(chunk["tokens"]):
        raise ValueError(
            f"Prediction length mismatch.\n"
            f"Model returned {len(pred_labels)} token-label pairs,\n"
            f"but input chunk contains {len(chunk['tokens'])} tokens."
        )

    for i, (pred_pair, gold_token) in enumerate(zip(pred_labels, chunk["tokens"])):

        # validate structure
        if not isinstance(pred_pair, list) or len(pred_pair) != 2:
            raise ValueError(
                f"Invalid prediction format at index {i}: {pred_pair}"
            )

        pred_token, pred_label = pred_pair

        # validate token preservation
        if pred_token != gold_token:
            raise ValueError(
                f"Token mismatch at index {i}.\n"
                f"Predicted token: {pred_token!r}\n"
                f"Gold token: {gold_token!r}"
            )

        # validate label
        if pred_label not in allowed_labels:
            raise ValueError(
                f"Invalid label at index {i}: {pred_label}"
            )

    return True
        

# use the model to annotate a chunk of tokens and return the predicted labels as a nested list [["token", "label"], ...] but no sentence boundaries
def annotate_chunk(prompt_template, chunk, model_info, temperature):
    chunk_tokens = chunk["tokens"]
    prompt = prompt_template.replace("{test_input}", json.dumps(chunk_tokens))

    for attempt in range(3):

        # model 1
        if model_info["backend"] == "openai":
            # prepare the prompt for the open ai API 

            response = model_info["client"].chat.completions.create(
                model=model_info["model_name"],
                messages=[{"role": "user", "content": prompt}],
                temperature=temperature
            )

            # extract the predicted labels from the response
            outputs = response.choices[0].message.content.strip()


        # model 2
        elif model_info["backend"] == "hf":
            # prepare the input for the Hugging Face model
            tokenizer = model_info["tokenizer"]
            inputs = tokenizer(prompt, return_tensors="pt").to(model_info["model"].device)

            with torch.no_grad():
                outputs = model_info["model"].generate(**inputs, max_new_tokens=chunk["size"]*4, do_sample=False)

            input_len = inputs["input_ids"].shape[-1]
            generated_tokens = outputs[0][input_len:]
            outputs = tokenizer.decode(generated_tokens, skip_special_tokens=True)

        # model 3
        else:
            raise ValueError(f"Unsupported model name: {model_info['model_name']}. Supported options are: mistral, llama, gpt 5-4.")
        
                
        # parse json to valid list, otherwise retry with a more explicit prompt
        try:
            pred_labels = json.loads(outputs)

        except json.JSONDecodeError as e:
            if "Extra data" in str(e):
                
                # manually post-processing LLM output cutting off the extra ] } at the end 
                print(f"\nDetected 'Extra data' JSON parsing error. Attempting to recover valid JSON from the output...\n")
                error_pos = e.pos
                repaired = outputs[:error_pos].strip()
                
                try:
                    pred_labels = json.loads(repaired)

                except json.JSONDecodeError:
                    raise ValueError(f"JSON parsing failed and could not be recovered.\n")

            else:
                raise ValueError(
                    f"JSON parsing failed on attempt {attempt+1}\n"
                    f"Error: {e}"
                    f"Raw output:\n{outputs}"
                )
                

            # give up after 3 attempts and print the raw output for debugging
            if attempt == 2:
                raise ValueError(
                    f"Maximum attempts reached.\n"
                    f"Failed to parse model output.\n\n"
                    f"Raw output:\n{outputs}"
                )

            # if retrying, be more explicit in the prompt about what to fix 
            prompt += (
                "\n\nYour previous output was invalid.\n"
                f"Parsing error:\n{str(e)}\n\n"
                "Return ONLY valid JSON.\n"
                "Do not include explanations.\n"
            )

            time.sleep(2)
            print("Retrying...\n")

            continue # retry immediately 
            
                
        try:
            validate_response(pred_labels, chunk)
            return pred_labels # if validation passes, return immediately

        except ValueError as e:

            print(f"\nValidation failed on attempt {attempt+1}")
            print(f"Error: {e}")
            print(f"Raw output:\n{outputs}")

            if attempt == 2:
                raise ValueError(
                    f"Maximum attempts reached.\n"
                    f"Failed to obtain valid annotation.\n\n"
                    f"Last output:\n{outputs}"
                )

            prompt += (
                "\n\nYour previous output was invalid.\n"
                f"Validation error:\n{str(e)}\n\n"
                "You MUST preserve tokens exactly.\n"
                "Return ONLY valid JSON.\n"
                "Do not modify tokens.\n"
                "Do not include explanations.\n"
            )

            print("Retrying...\n")
            time.sleep(2)


def reconstruct_labels(pred_pairs, chunk):
    nested_labels = []
    start = 0

    for sent_len in chunk["sent_lengths"]:
        end = start + sent_len

        sentence_pairs = pred_pairs[start:end]
        sentence_labels = [label for _, label in sentence_pairs]

        nested_labels.append(sentence_labels)
        start = end

    return nested_labels

##### ----------------------------- MAIN SCRIPT -------------------------------------- #####

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--model_name", default="mistral")
    parser.add_argument("--quantized", action="store_true", help="Whether to load the model in 4-bit quantized mode for memory efficiency.")
    parser.add_argument("--mode", default="validate")
    parser.add_argument("--create_chunks", action="store_true")
    parser.add_argument("--max_chunk_size", type=int, default=250, help="Maximum number of words to include in each chunk sent to the model for annotation.")
    parser.add_argument("--temperature", type=float, default=0)
    parser.add_argument("--input_data", default="annotation/FIN5_validation.txt")
    parser.add_argument("--output_dir", default="annotation/validation_scores/")
    parser.add_argument("--output_file", required=True)

    args = parser.parse_args()
    model_name = args.model_name.lower()
    quantized = args.quantized

    model = load_model(model_name, quantized)

    if args.mode == "validate":
        print("Running in VALIDATION mode. Predictions will be compared against true labels from the last contract in FIN5 and evaluation metrics will be saved to the output file.\n")

        # load validation data
        if args.create_chunks:

            sentences, true_labels = parse_iob2_file(args.input_data)

            print("Creating chunks from sentences...\n")
            chunks = build_chunks(
                sentences,
                labels=true_labels,
                max_chunk_size=args.max_chunk_size
            )

            # since the output of creating chunks is deterministic, we can save it to reuse 
            with open("annotation/chunks.json", "w", encoding="utf-8") as f:
                json.dump(chunks, f, ensure_ascii=False, indent=4)

        else:
            print("Loading chunks from file...\n")
            with open("annotation/chunks.json", "r", encoding="utf-8") as f:
                chunks = json.load(f)

        
        print(f"Loading prompt template...\n")
        prompt_template = format_prompt("annotation/prompt_annotation.txt", "annotation/one_shot.txt")

        pred_labels = []
        true_labels = []
        
        for chunk in chunks:
            chunk_labels = annotate_chunk(prompt_template, chunk, model, args.temperature)
            nested_labels = reconstruct_labels(chunk_labels, chunk)
            gold_labels = chunk["gold_labels"]
            pred_labels.extend(nested_labels)
            true_labels.extend(gold_labels)

        # evaluate predictions against true labels and save results to file
        output = evaluate_predictions(true_labels, pred_labels)

    else:
        print("Running in ANNOTATION mode. Predictions will be saved to the output file.\n")


    # create output dir from args
    os.makedirs(args.output_dir, exist_ok=True)
    output_path = os.path.join(args.output_dir, args.output_file)

    # Save to file
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=4)

    print(f"Results saved to {output_path}")